# Generated by Django 3.1.6 on 2021-02-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wink_landing', '0002_auto_20210225_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wink_landing.comment'),
        ),
    ]
