# Generated by Django 3.1.6 on 2021-02-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wink_landing', '0006_auto_20210227_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='createddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='createddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='createddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='createddate',
            field=models.DateTimeField(),
        ),
    ]
